# Generated by Django 5.0 on 2023-12-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=256)),
                ('type_tern_id', models.IntegerField()),
                ('sample_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=30)),
                ('core_prompt', models.TextField()),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_passed', models.URLField()),
                ('prompt_generated', models.TextField()),
                ('result', models.JSONField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='formatter.endpoints')),
            ],
        ),
    ]
