# Generated by Django 5.0 on 2023-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
