# Generated by Django 4.2.8 on 2023-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalcall',
            name='json_payload',
        ),
        migrations.AddField(
            model_name='externalcall',
            name='text_payload',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
