# Generated by Django 4.2.8 on 2023-12-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_prompt_ai_model_aimodel_price_per_1ktoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoints',
            new_name='Endpoint',
        ),
    ]
