# Generated by Django 4.2.8 on 2023-12-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_endpoint_description_externalcall_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalcall',
            old_name='endpoint_id',
            new_name='endpoint',
        ),
    ]
