# Generated by Django 4.2.8 on 2023-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_apicall_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='response',
            field=models.JSONField(blank=True),
        ),
    ]
