# Generated by Django 4.2.8 on 2023-12-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_apicall_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicall',
            old_name='response',
            new_name='response_JSON',
        ),
    ]
