# Generated by Django 4.2.8 on 2023-12-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_response_json_apicall_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcall',
            name='tern_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
