# Generated by Django 4.2.8 on 2023-12-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_externalcall_tern_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='source_call',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.externalcall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpoint',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
