# Generated by Django 4.2.8 on 2023-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_prompt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='required_response_keys',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
