# Generated by Django 4.2.8 on 2023-12-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_prompt_required_response_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='error_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apicall',
            name='valid_resopnse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
