# Generated by Django 4.2.8 on 2023-12-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_prompt_ai_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='ai_temperature',
            field=models.IntegerField(),
        ),
    ]
