# Generated by Django 4.2.8 on 2023-12-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_apifiles_externalcall_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIFiles',
        ),
    ]
