# Generated by Django 4.2.8 on 2024-01-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_aimodel_largest_token_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='required_response_keys',
            field=models.JSONField(blank=True),
        ),
    ]
